version: "3.9"
services:
  jxlog:
    image: "hkccr.ccs.tencentyun.com/jxwaf/jxlog:v1_debug"
    ports:
      - "8877:8877"
    environment:
      CLICKHOUSE: clickhouse:9000
      Database: jxwaf
      USERNAME: jxlog
      PASSWORD: jxlog
      TCPSERVER: 0.0.0.0
    restart: always
  clickhouse:
    image: "clickhouse/clickhouse-server:latest"
    environment:
      CLICKHOUSE_DB: jxwaf
      CLICKHOUSE_USER: jxlog
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: jxlog
    restart: always

